---
name: new-prs
up:
- ruby: 2.3.1
- bundler
# - database:
#     bootstrap: bin/rake db:setup ; bin/rake db:test:prepare
#     migrate: bin/rake db:migrate db:test:prepare
#     host: jrubytest.railgun
#     user: root
#     password: ''
#     database: jrubytest_development
commands:
  test: bundle exec rspec

packages:
  - git@github.com:Shopify/dev-shopify.git

